# Generated by Django 5.2.3 on 2025-07-13 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estore',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
