# Generated by Django 5.2.3 on 2025-07-17 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_review_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='email',
            field=models.EmailField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.CharField(null=True),
        ),
    ]
