# Generated by Django 5.2.3 on 2025-07-15 07:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='order_update',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='account',
            name='promotion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='subscribe',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL),
        ),
    ]
